package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.AmazonEC2CloudProfile
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.amazonEC2CloudProfile
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AmazonEC2CloudProfile> {
            amazonEC2CloudProfile {
                id = "amazon-2"
                name = "Test"
                terminateIdleMinutes = 0
                region = AmazonEC2CloudProfile.Regions.EU_WEST_DUBLIN
                awsConnectionId = "AwsExample_StaticCredentialsSession"
                authType = accessKey {
                    keyId = "credentialsJSON:eb866efa-5965-49be-b5be-6ddeb4c55c2f"
                    secretKey = "credentialsJSON:1448a0c5-1c49-48a5-980d-7a2612a7da20"
                }
            }
        }
        feature1.apply {
            enabled = false
            name = "Test"
            terminateIdleMinutes = 0
            region = AmazonEC2CloudProfile.Regions.EU_WEST_DUBLIN
            awsConnectionId = "AwsExample_StaticCredentialsSession"
        }
    }
}
